name: Cleanup Koyeb application

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"

      - name: Cleanup Koyeb application
        uses: koyeb/action-git-deploy/cleanup@v1
        with:
          app-name: expressjs-${{ github.event.ref }}
