name: Build and deploy the application to Koyeb

on:
##  schedule:
##    - cron: '55 7 * * *'
  # push:
  #   branches:
  #     - main

  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy'
        required: true  

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_TOKEN }}"

      - name: Build and deploy the application
        uses: koyeb/action-git-deploy@v1
        with:
          app-name:       naval-kanya
          service-ports:  "3000:http"
          service-routes: "/:3000"
          skip-cache:     true
